// USER ACTION TYPES
export const SET_USER = 'SET_USER';
export const CLEAR_USER = 'CLEAR_USER';

// CHANNEL ACTION TYPES
export const SET_CURRENT_CHANNEL = 'SET_CURRENT_CHANNEL';
export const SET_PRIVATE_CHANNEL = 'SET_PRIVATE_CHANNEL';
export const SET_USER_POSTS_COUNT = 'SET_USER_POSTS_COUNT';

// COLORS ACTION TYPES
export const SET_APPLICATION_COLORS = 'SET_APPLICATION_COLORS';
